default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: <%= ENV['SCAVENGER_DB_USER'] %>
  password: <%= ENV['SCAVENGER_DB_PASS'] %>

development:
  <<: *default
  database: <%= ENV['SCAVENGER_DB_NAME'] %>

test:
  <<: *default
  database: <%= ENV['TEST_SCAVENGER_DB_NAME'] %>

